/**
 * Health-verdict builder, validator, and writer. Builds .health.json
 * payloads from a manifest (preferred) or a content scan (fallback),
 * validates against schema/health.schema.json, and writes pretty-printed
 * JSON to disk. Spec: docs/superpowers/specs/2026-06-10-manifest-and-health-design.md §3, §3.4.
 */

import { writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';
import Ajv from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import {
  weightsForTier,
  readiness as computeReadiness,
  tierLabel,
  confidence as computeConfidence,
  weightedCounts,
} from './tier-weights.js';
import { classifyFile } from './file-status.js';
import { suggestedAction } from './gap-actions.js';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const SCHEMA_PATH = resolve(__dirname, '../../../schema/health.schema.json');
const schema = JSON.parse(readFileSync(SCHEMA_PATH, 'utf-8'));

const ajv = new Ajv({ allErrors: true, strict: true });
addFormats(ajv);
const validate = ajv.compile(schema);

const GENERATOR_PREFIX = 'brand-cli';
let cachedVersion = null;
function generatorString() {
  if (cachedVersion) return cachedVersion;
  const pkgPath = resolve(__dirname, '../../../package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
  cachedVersion = `${GENERATOR_PREFIX}@${pkg.version}`;
  return cachedVersion;
}

/**
 * Build a health payload from a manifest (preferred) or from a content scan
 * of `.brand/`. Returns the full payload object — does not write to disk.
 */
export function buildHealth({ manifest, brandDir, tier, client, now }) {
  const generated_at = now ?? new Date().toISOString();

  let resolvedTier;
  let resolvedClient;
  let files;
  let downgrades = [];
  let manifest_seen = false;
  let manifest_generated_at;

  if (manifest) {
    resolvedTier = manifest.tier;
    resolvedClient = manifest.client;
    files = Object.fromEntries(
      Object.entries(manifest.files).map(([p, entry]) => [p, entry.status])
    );
    downgrades = Object.entries(manifest.files)
      .filter(([, entry]) => entry.status === 'defaults')
      .map(([file, entry]) => ({ file, reason: entry.note ?? 'producer-marked defaults' }));
    manifest_seen = true;
    manifest_generated_at = manifest.generated_at;
  } else {
    if (!brandDir || !tier) {
      throw new Error('buildHealth requires either {manifest} or {brandDir, tier}');
    }
    resolvedTier = tier;
    resolvedClient = client;
    const weights = weightsForTier(tier);
    files = {};
    for (const path of Object.keys(weights)) {
      files[path] = classifyFile(join(brandDir, path));
    }
  }

  const weights = weightsForTier(resolvedTier);
  const r = computeReadiness(files, weights);
  const { weightedComplete, weightedTotal, completeCount, totalCount } = weightedCounts(files, weights);

  const hasDefaults = downgrades.length > 0;
  // Per spec section 3 (.health.json): "MEDIUM when ... manifest absent and >=80%
  // files complete by content scan." That's an *unweighted* file-count ratio
  // (count, not weight) — distinct from `readiness` which is weighted.
  const scanCompleteRatio = totalCount === 0 ? 0 : completeCount / totalCount;
  const conf = computeConfidence({ manifestSeen: manifest_seen, hasDefaults, scanCompleteRatio });

  const gaps = Object.entries(weights)
    .filter(([p]) => ['partial', 'placeholder', 'missing'].includes(files[p]))
    .map(([file]) => ({
      file,
      status: files[file],
      suggested_action: suggestedAction(file, files[file]),
    }));

  const out = {
    _comment: 'Generated by brand-cli score. Do not hand-edit.',
    version: '1',
    generated_at,
    generator: generatorString(),
    tier: resolvedTier,
    readiness: r,
    tier_label: tierLabel(r),
    manifest_seen,
    weights,
    weighted_complete: weightedComplete,
    weighted_total: weightedTotal,
    confidence: conf,
    files,
    gaps,
    downgrades,
  };

  if (resolvedClient) out.client = resolvedClient;
  if (manifest_generated_at) out.manifest_generated_at = manifest_generated_at;

  return out;
}

/**
 * Validate a health payload against schema/health.schema.json. Returns { valid, errors, errorText }.
 */
export function validateHealth(payload) {
  const valid = validate(payload);
  if (valid) return { valid: true, errors: null, errorText: null };
  return {
    valid: false,
    errors: validate.errors,
    errorText: ajv.errorsText(validate.errors),
  };
}

/**
 * Validate then write a health payload as pretty-printed JSON with trailing newline. Throws on validation failure.
 */
export function writeHealth(absPath, payload) {
  const result = validateHealth(payload);
  if (!result.valid) {
    throw new Error(`.health.json failed schema validation: ${result.errorText}`);
  }
  writeFileSync(absPath, JSON.stringify(payload, null, 2) + '\n');
}
